language: python

python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r docs/requirements.txt
  - pip install "dask[dataframe]"   # Install requirements for dask dataframe

# command to run tests
script:
  - pytest