package:
  name: pyxpcm
  version: "0.4"

source:
  git_rev: v0.4
  git_url: https://github.com/obidam/pyxpcm

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    -

about:
  home: https://github.com/obidam/pyxpcm
  license: GPLv3
  license_file: LICENSE.txt